spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///E:/Poli2022-1/Cloud/Repos/StoreMultiprojectConfigData
  security:
    user:
      name: ${CONFIG_USER}
      password: ${CONFIG_PASSWORD}
server:
  port: 9000

